name = "Void & Draconic"
author = "Stefan"
version = "0.5.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ae062adc7e80ee0f631fac118c4374142b4be3e59327a4853609511d44e6645"

[versions]
forge = "47.4.26"
minecraft = "1.20.1"
