name = "Void & Draconic"
author = "Stefan"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d951f55a7ae7d5fa8884a556fbf464e1ac12bb48ae2a506941ccf2d60feb2a9"

[versions]
forge = "47.4.26"
minecraft = "1.20.1"
